// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/andreis3/users-ms/src/application/operation/user/interface (interfaces: ICreateUserOperation)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/andreis3/users-ms/src/application/operation/user/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockICreateUserOperation is a mock of ICreateUserOperation interface.
type MockICreateUserOperation struct {
	ctrl     *gomock.Controller
	recorder *MockICreateUserOperationMockRecorder
}

// MockICreateUserOperationMockRecorder is the mock recorder for MockICreateUserOperation.
type MockICreateUserOperationMockRecorder struct {
	mock *MockICreateUserOperation
}

// NewMockICreateUserOperation creates a new mock instance.
func NewMockICreateUserOperation(ctrl *gomock.Controller) *MockICreateUserOperation {
	mock := &MockICreateUserOperation{ctrl: ctrl}
	mock.recorder = &MockICreateUserOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreateUserOperation) EXPECT() *MockICreateUserOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockICreateUserOperation) Execute(arg0 *dto.UserInputDTO) (*dto.UserOutPutDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(*dto.UserOutPutDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockICreateUserOperationMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockICreateUserOperation)(nil).Execute), arg0)
}
