// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/andreis3/users-ms/src/application/operation/user/interface (interfaces: IDeleteUserOperation)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIDeleteUserOperation is a mock of IDeleteUserOperation interface.
type MockIDeleteUserOperation struct {
	ctrl     *gomock.Controller
	recorder *MockIDeleteUserOperationMockRecorder
}

// MockIDeleteUserOperationMockRecorder is the mock recorder for MockIDeleteUserOperation.
type MockIDeleteUserOperationMockRecorder struct {
	mock *MockIDeleteUserOperation
}

// NewMockIDeleteUserOperation creates a new mock instance.
func NewMockIDeleteUserOperation(ctrl *gomock.Controller) *MockIDeleteUserOperation {
	mock := &MockIDeleteUserOperation{ctrl: ctrl}
	mock.recorder = &MockIDeleteUserOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeleteUserOperation) EXPECT() *MockIDeleteUserOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIDeleteUserOperation) Execute(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockIDeleteUserOperationMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIDeleteUserOperation)(nil).Execute), arg0)
}
