// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/andreis3/users-ms/src/application/operation/user/interface (interfaces: IGetIdUserOperation)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/andreis3/users-ms/src/application/operation/user/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockIGetIdUserOperation is a mock of IGetIdUserOperation interface.
type MockIGetIdUserOperation struct {
	ctrl     *gomock.Controller
	recorder *MockIGetIdUserOperationMockRecorder
}

// MockIGetIdUserOperationMockRecorder is the mock recorder for MockIGetIdUserOperation.
type MockIGetIdUserOperationMockRecorder struct {
	mock *MockIGetIdUserOperation
}

// NewMockIGetIdUserOperation creates a new mock instance.
func NewMockIGetIdUserOperation(ctrl *gomock.Controller) *MockIGetIdUserOperation {
	mock := &MockIGetIdUserOperation{ctrl: ctrl}
	mock.recorder = &MockIGetIdUserOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGetIdUserOperation) EXPECT() *MockIGetIdUserOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIGetIdUserOperation) Execute(arg0 string) (*dto.UserOutPutDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(*dto.UserOutPutDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIGetIdUserOperationMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIGetIdUserOperation)(nil).Execute), arg0)
}
