// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/andreis3/users-ms/src/domain/factory (interfaces: RepositoryFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	repository "github.com/andreis3/users-ms/src/domain/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryFactory is a mock of RepositoryFactory interface.
type MockRepositoryFactory struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryFactoryMockRecorder
}

// MockRepositoryFactoryMockRecorder is the mock recorder for MockRepositoryFactory.
type MockRepositoryFactoryMockRecorder struct {
	mock *MockRepositoryFactory
}

// NewMockRepositoryFactory creates a new mock instance.
func NewMockRepositoryFactory(ctrl *gomock.Controller) *MockRepositoryFactory {
	mock := &MockRepositoryFactory{ctrl: ctrl}
	mock.recorder = &MockRepositoryFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryFactory) EXPECT() *MockRepositoryFactoryMockRecorder {
	return m.recorder
}

// CreateUserRepository mocks base method.
func (m *MockRepositoryFactory) CreateUserRepository() repository.UserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserRepository")
	ret0, _ := ret[0].(repository.UserRepository)
	return ret0
}

// CreateUserRepository indicates an expected call of CreateUserRepository.
func (mr *MockRepositoryFactoryMockRecorder) CreateUserRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserRepository", reflect.TypeOf((*MockRepositoryFactory)(nil).CreateUserRepository))
}
