// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/andreis3/users-ms/src/domain/factory (interfaces: IRepositoryFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	repository "github.com/andreis3/users-ms/src/domain/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockIRepositoryFactory is a mock of IRepositoryFactory interface.
type MockIRepositoryFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryFactoryMockRecorder
}

// MockIRepositoryFactoryMockRecorder is the mock recorder for MockIRepositoryFactory.
type MockIRepositoryFactoryMockRecorder struct {
	mock *MockIRepositoryFactory
}

// NewMockIRepositoryFactory creates a new mock instance.
func NewMockIRepositoryFactory(ctrl *gomock.Controller) *MockIRepositoryFactory {
	mock := &MockIRepositoryFactory{ctrl: ctrl}
	mock.recorder = &MockIRepositoryFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepositoryFactory) EXPECT() *MockIRepositoryFactoryMockRecorder {
	return m.recorder
}

// CreateUserRepository mocks base method.
func (m *MockIRepositoryFactory) CreateUserRepository() repository.IUserRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserRepository")
	ret0, _ := ret[0].(repository.IUserRepository)
	return ret0
}

// CreateUserRepository indicates an expected call of CreateUserRepository.
func (mr *MockIRepositoryFactoryMockRecorder) CreateUserRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserRepository", reflect.TypeOf((*MockIRepositoryFactory)(nil).CreateUserRepository))
}
