// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/andreis3/users-ms/src/application/operation/user/interface (interfaces: IUpdateUserOperation)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/andreis3/users-ms/src/application/operation/user/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockIUpdateUserOperation is a mock of IUpdateUserOperation interface.
type MockIUpdateUserOperation struct {
	ctrl     *gomock.Controller
	recorder *MockIUpdateUserOperationMockRecorder
}

// MockIUpdateUserOperationMockRecorder is the mock recorder for MockIUpdateUserOperation.
type MockIUpdateUserOperationMockRecorder struct {
	mock *MockIUpdateUserOperation
}

// NewMockIUpdateUserOperation creates a new mock instance.
func NewMockIUpdateUserOperation(ctrl *gomock.Controller) *MockIUpdateUserOperation {
	mock := &MockIUpdateUserOperation{ctrl: ctrl}
	mock.recorder = &MockIUpdateUserOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUpdateUserOperation) EXPECT() *MockIUpdateUserOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIUpdateUserOperation) Execute(arg0 string, arg1 *dto.UserInputDTO) (*dto.UserOutPutDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(*dto.UserOutPutDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIUpdateUserOperationMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIUpdateUserOperation)(nil).Execute), arg0, arg1)
}
