// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/andreis3/users-ms/src/interface/http/presentation/user (interfaces: IUserController)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockIUserController is a mock of IUserController interface.
type MockIUserController struct {
	ctrl     *gomock.Controller
	recorder *MockIUserControllerMockRecorder
}

// MockIUserControllerMockRecorder is the mock recorder for MockIUserController.
type MockIUserControllerMockRecorder struct {
	mock *MockIUserController
}

// NewMockIUserController creates a new mock instance.
func NewMockIUserController(ctrl *gomock.Controller) *MockIUserController {
	mock := &MockIUserController{ctrl: ctrl}
	mock.recorder = &MockIUserControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserController) EXPECT() *MockIUserControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUserController) Create(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", arg0)
}

// Create indicates an expected call of Create.
func (mr *MockIUserControllerMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserController)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIUserController) Delete(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", arg0)
}

// Delete indicates an expected call of Delete.
func (mr *MockIUserControllerMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIUserController)(nil).Delete), arg0)
}

// GetAll mocks base method.
func (m *MockIUserController) GetAll(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAll", arg0)
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIUserControllerMockRecorder) GetAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIUserController)(nil).GetAll), arg0)
}

// GetID mocks base method.
func (m *MockIUserController) GetID(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetID", arg0)
}

// GetID indicates an expected call of GetID.
func (mr *MockIUserControllerMockRecorder) GetID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockIUserController)(nil).GetID), arg0)
}

// Update mocks base method.
func (m *MockIUserController) Update(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", arg0)
}

// Update indicates an expected call of Update.
func (mr *MockIUserControllerMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUserController)(nil).Update), arg0)
}
