name: users-ms-ci

on:
  push:
    branches: [ feat/*, fix/*, hotfix/*, chore/* ]
  pull_request:
    branches: [ master, develop, preprod ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test Unit Coverage
        run: make unit-tests-coverage-report

      - name: Test Unit Verbose
        run: make test-unit-verbose
