name: users-ms-ci

on:
  push:
    branches: [ feat/*, fix/*, hotfix/*, chore/* ]
  pull_request:
    branches: [ develop, preprod, master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Dependencies
        run:  go mod download

      - name: Install Ginkgo
        run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo

      - name: Test Unit Coverage
        run: make unit-tests-report

      - name: Test Unit Verbose
        run: make unit-tests-verbose
